#! /bin/sh
killall -9 xhkd dunst ksuperkey xfce4-power-manager bspc

# Enable power management
xfce4-power-manager &

# Fix cursor
xsetroot -cursor_name left_ptr
polybar -q example -c ~/.config/bspwm/polybar/config &
#hsetroot -cover ~/Pictures/everforest-walls/fog_forest_2.png
~/.fehbg &
picom -b
dunst &
mpd & disown
xfce4-power-manager &
/usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1 &
sxhkd -c ~/.config/bspwm/sxhkdrc &
#pgrep -x sxhkd > /dev/null || sxhkd -c ~/.config/bspwm/sxhkdrc &

workspaces() {
	name=1
	for monitor in `bspc query -M`; do
		#bspc monitor ${monitor} -n "$name" -d 'I' 'II' 'III' 'IV' 'V' 'VI' 'VII' 'VIII' 'XI'

		bspc monitor ${monitor} -n "$name" -d '' '' '󰈮' '' '' '' '' '' '' ''
		let name++
	done
}
workspaces

bspc config border_width         2
bspc config window_gap           5

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off
